### ISSUE TITLE
Redshift systray color

### ISSUE THREAD

**Issue by janos-r** [germanfr/new-minty#1]
Issue:
The Redshift icon color in the right-side is now black instead of white.

Suspected cause:
In 19.1 the Redshift icon was changed to behave more like a "symbolic icon". This was mentioned in the changelog to 19.1. Before this, the icon was white and good to see, now it's black, but only on NewMinty. On dark-y it's white.

Scrnshot attached.
![screenshot from 2019-01-02 18-14-48](https://user-images.githubusercontent.com/30606201/50603578-41f8ac00-0ebb-11e9-87c9-b77df7261cf8.png)

Note:
The icon apears white after switching to dark-y and restarting the app and switching back to newMinty. But after a new login, the app is still black.

**Comment by germanfr** [comment]
What icon theme is that? My icon for redshift is different, it's not symbolic. Tray icons are not symbolic and the color of non-symbolic icons can't be changed.

![screenshot from 2019-01-02 20-02-30](https://user-images.githubusercontent.com/10391266/50607430-75dace00-0ec9-11e9-88e0-e4efbef17cff.png)

**Comment by germanfr** [comment]
Oh, is that the cinnamon applet?

**Comment by germanfr** [comment]
Do you say on Mint-Y the icon is white? I see it black no matter the theme.

**Comment by janos-r** [comment]
The icon theme in my scrnshot is the default mint-y.
Desktop theme of course newMinty. Different icon color in desktop theme "mint-y-dark" (for ex.).
I can see this red bulb icon in your example when changing the icon theme to mint-x.
This concerns the Redshift program that is preinstalled, not the applet that you can add to the panel.

**Comment by germanfr** [comment]
Well now I understand. This icon is not symbolic so cannot be colored. It just turns out it is black or white (or red) depending on the icon theme. This is not something that is fixable within a cinnamon theme. My Mint-Y-icons version is 1.3.3-1, maybe it has been changed from black to white in the icon theme, but my icon is white (even on white themes). You have to file an issue against the Mint-Y icon theme.
